title: mavilam site
author: Miguel Ávila Monroy
email: miguel . avila . monroy [at] gmail . com
description: >- # this means to ignore newlines until "baseurl:"
  This is my attemp of a personal site with ❤.
greeting: "Hey Welcome! this is Miguel! 👋"
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
social_link: twitter
social_username: avilamonroy
github_username:  mavilam

# Google Analytics
google_analytics: UA-110469955-1

# Build settings
markdown: kramdown
theme: mavilam-minimal
plugins:
  - jekyll-feed
  - jekyll-analytics
