title: mavilam site
author: Miguel Ávila Monroy
email: miguel . avila . monroy [at] gmail . com
description: >- # this means to ignore newlines until "baseurl:"
  This is my attemp of a personal site with ❤.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
social_link: twitter
social_username: avilamonroy
github_username:  mavilam

jekyll_analytics:
  GoogleAnalytics:
    id: UA-110469955-1
    anonymizeIp: false

# Build settings
markdown: kramdown
theme: jekyll-swiss
plugins:
  - jekyll-feed
  - jekyll-analytics
